// Generated by CoffeeScript 1.10.0
(function() {
  var a5, age, arrg, err, error, fun, fun2, i, isRight, isStudent, item, len, nume, obj, str;

  nume = 1;

  obj = {
    name: 2,
    "var": 3
  };

  fun = function() {
    return obj.name + nume;
  };

  fun2 = function(name, age) {
    if (age == null) {
      age = 20;
    }
    return console.log(name + ':' + age);
  };

  isRight = true;

  str = 'str';

  if (isRight) {
    str += 'hha';
  }

  age = 19;

  isStudent = (18 < age && age < 25);

  arrg = [1, 2, 4];

  for (i = 0, len = arrg.length; i < len; i++) {
    item = arrg[i];
    console.log(item);
  }

  if (str == null) {
    str = "aaa";
  }

  try {
    a5 = abc;
  } catch (error) {
    err = error;
    console.log(err);
  } finally {
    console.log('f');
  }

}).call(this);

//# sourceMappingURL=test.js.map
